### ISSUE TITLE
Seems like plugin is not working now

### ISSUE THREAD

**Issue by RevertIT** [weex/mybb-credit-from-coins#1]
Hello @weex,

I just tested the plugin and there are several errors in PHP 7.2 and after fixing it and entering blockchain API, it shows the generic message that it can't connect to the blockchain api. I think this plugin needs a bit of update.

Thank you

**Comment by weex** [comment]
If you'd like to create a pull request with your changes, merging it is probably the best I can do. I'm no longer running a test server for this and have no plans. 

The best way forward is to choose another blockchain data source (preferably one that you can run yourself) that has callbacks and convert the code to work with the new API. You might look in to blocknotify or ZeroMQ in Bitcoin Core.
